src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: OperationRepository::class)]
class Operation
{

  

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
     

    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
     
    
  
    public ?\DateTimeInterface $date_operation = null;

    #[ORM\Column(length: 255)]
    
     #[Assert\NotBlank(message:"Operation/Vaccination/Surgury/Autre")]
     #[Assert\Choice(['Operation', 'Vaccination', 'Surgury'])]
    
    public ?string $type_operation = null;

    #[ORM\Column(length: 255)]
    
     #[Assert\NotBlank]
     #[Assert\Length(
           min : 2,
           max : 50,
           minMessage : "Le nom du médecin doit contenir au moins {{ limit }} caractères",
           maxMessage : "Le nom du médecin doit contenir moins de {{ limit }} caractères"
      )]

    public ?string $nom_medecin = null;

    #[ORM\Column]
        
    #[Assert\NotBlank]
    #[Assert\Type(
          type:"numeric",
          message:"Le coût de l'opération doit être un nombre"
      )]
    #[Assert\Positive(
          message:"Le coût de l'opération doit être un nombre positif"
     )]

    public ?int $cout_operation = null;

    
    #[ORM\Column(length: 255)]
    
    #[Assert\NotBlank]
    #[Assert\Length(
          min : 7,
          max : 100,
          minMessage : "La note doit contenir au moins {{ limit }} caractères",
          maxMessage : "La note doit contenir moins de {{ limit }} caractères"
     )]
    public ?string $note_operation = null;

    #[ORM\ManyToOne(inversedBy: 'Operation')]
    public ?Maladie $maladie = null;

    #[ORM\ManyToOne(inversedBy: 'operations')]
    public ?Animal $animal = null;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateOperation(): ?\DateTimeInterface
    {
        return $this->date_operation;
    }

    public function setDateOperation(\DateTimeInterface $date_operation): self
    {
        $this->date_operation = $date_operation;

        return $this;
    }

    public function getTypeOperation(): ?string
    {
        return $this->type_operation;
    }

    public function setTypeOperation(string $type_operation): self
    {
        $this->type_operation = $type_operation;

        return $this;
    }

    public function getNomMedecin(): ?string
    {
        return $this->nom_medecin;
    }

    public function setNomMedecin(string $nom_medecin): self
    {
        $this->nom_medecin = $nom_medecin;

        return $this;
    }

    public function getCoutOperation(): ?int
    {
        return $this->cout_operation;
    }

    public function setCoutOperation(int $cout_operation): self
    {
        $this->cout_operation = $cout_operation;

        return $this;
    }

    public function getNoteOperation(): ?string
    {
        return $this->note_operation;
    }

    public function setNoteOperation(string $note_operation): self
    {
        $this->note_operation = $note_operation;

        return $this;
    }

    public function getMaladie(): ?Maladie
    {
        return $this->maladie;
    }

    public function setMaladie(?Maladie $maladie): self
    {
        $this->maladie = $maladie;

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->animal;
    }

    public function setAnimal(?Animal $animal): self
    {
        $this->animal = $animal;

        return $this;
    }
}

src/Form/OperationType.php
<?php

namespace App\Form;

use App\Entity\Operation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use App\Form\Transformer;

class OperationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_operation', DateTimeType::class, [
                
                'label' => 'Date et heure',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('type_operation', ChoiceType::class,[ 'choices' => [
                'Surgury' => 'Surgury',
                'Vaccination' => 'Vaccination',
                'Operation' => 'Operation',
                'Autre' => 'Autre'
            ],
            'attr' => [
                'class' => 'form-control mb-3',
            ],])
            ->add('nom_medecin',TextType::class,[ 'attr' => [
                'class' => 'form-control mb-3',
            ],])
            ->add('cout_operation', IntegerType::class, [
                'label' => 'Coût de l\'opération',
                'attr' => [
                    'min' => 0,
                    'step' => 1,
                ],
            ])
            ->add('note_operation',TextareaType::class,[ 'attr' => [
                'class' => 'form-control mb-3',
            ],])
            ->add('maladie')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Operation::class,
        ]);
    }
}

src/Controller/OperationController.php
<?php

namespace App\Controller;
use App\Entity\Operation;
use App\Form\OperationType;
use App\Repository\OperationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/operation')]
class OperationController extends AbstractController
{
    #[Route('/', name: 'app_operation_index', methods: ['GET'])]
    public function index(OperationRepository $operationRepository): Response
    {
        return $this->render('operation/index.html.twig', [
            'operations' => $operationRepository->findAll(),
        ]);
    }
    
    #[Route('/oper', name: 'app_operation_afficher', methods: ['GET'])]
    public function afficher(OperationRepository $operationRepository): Response
    {
        return $this->render('operation/afficher.html.twig', [
            'operations' => $operationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_operation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OperationRepository $operationRepository): Response
    {
        $operation = new Operation();
        $form = $this->createForm(OperationType::class, $operation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $operationRepository->save($operation, true);

            return $this->redirectToRoute('app_operation_afficher', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('operation/new.html.twig', [
            'operation' => $operation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_operation_show', methods: ['GET'])]
    public function show(Operation $operation): Response
    {
        return $this->render('operation/show.html.twig', [
            'operation' => $operation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_operation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Operation $operation, OperationRepository $operationRepository): Response
    {
        $form = $this->createForm(OperationType::class, $operation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $operationRepository->save($operation, true);

            return $this->redirectToRoute('app_operation_afficher', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('operation/edit.html.twig', [
            'operation' => $operation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_operation_delete', methods: ['POST'])]
    public function delete(Request $request, Operation $operation, OperationRepository $operationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$operation->getId(), $request->request->get('_token'))) {
            $operationRepository->remove($operation, true);
        }

        return $this->redirectToRoute('app_operation_afficher', [], Response::HTTP_SEE_OTHER);
    }
   
    
}

templates/operation/_delete_form.html.twig
<form method="post" action="{{ path('app_operation_delete', {'id': operation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ operation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/operation/_form.html.twig
{{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/operation/afficher.html.twig
{% extends 'base1.html.twig' %}

{% block title %}operations{% endblock %}

{% block body %}
    <h1>Operation </h1>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Date d'operation</th>
                <th>Type d'operation</th>
                <th>Nom du medecin</th>
                <th>Cout</th>
                <th>Notes</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for operation in operations %}
            <tr>
                <td>{{ operation.id }}</td>
                <td>{{ operation.dateOperation ? operation.dateOperation|date('Y-m-d') : '' }}</td>
                <td>{{ operation.typeOperation }}</td>
                <td>{{ operation.nomMedecin }}</td>
                <td>{{ operation.coutOperation }}</td>
                <td>{{ operation.noteOperation }}</td>
                <td>
                    <a href="{{ path('app_operation_show', {'id': operation.id}) }}">show</a>
                    <a href="{{ path('app_operation_edit', {'id': operation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_operation_new') }}">Create new</a>
{% endblock %}

templates/operation/edit.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Edit Operation{% endblock %}

{% block body %}
    <h1>Edit Operation</h1>

    {{ include('operation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_operation_afficher') }}">back to list</a>

    {{ include('operation/_delete_form.html.twig') }}
{% endblock %}

templates/operation/index.html.twig
{% extends 'front/base.html.twig' %} 

{% block title %}Operation index{% endblock %}

{% block body %}
<style>
  .mon-espace {
    margin: 20px;
  }
</style>

    <h1 class="mon-espace">LISTE DES OPERATIONS</h1>


    <section class="items-product1 pt-30">
        <div class="container">
            <div class="row">

                <input  id="myInput"  type="text" placeholder="search">
                <section class="items-product1 pt-30">
        <div class="container">
            
                <table class="table table-bordered" id="t"  width="100%" cellspacing="0">
                    <thead>
                    <tr>



                        <th>TYPE DE L'OPERATION</th>
                        <th>NOM DU MEDECIN</th>
                        <th>COUT</th>
                        <th>NOTES</th>
                    </tr>
                    </thead>

                    <tbody id="myTable">
                    {% for operation in operations %}
                        <tr>


                            <td>{{ operation.type_operation }}</td>
                            <td>{{ operation.nom_medecin }}</td>
                            <td>{{ operation.cout_operation }}</td>
                            <td>{{ operation.note_operation }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tbody id="search">
                    </tbody>
                </table>

            </div>
        </div>
    </section>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>






{% endblock %}

templates/operation/new.html.twig
{% extends 'base1.html.twig' %}

{% block title %}New Operation{% endblock %}

{% block body %}
    <h1>Create new Operation</h1>

    {{ include('operation/_form.html.twig') }}

    <a href="{{ path('app_operation_index') }}">back to list</a>
{% endblock %}

templates/operation/show.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Operation{% endblock %}

{% block body %}
    <h1>Operation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ operation.id }}</td>
            </tr>
            <tr>
                <th>Date_operation</th>
                <td>{{ operation.dateOperation ? operation.dateOperation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Type_operation</th>
                <td>{{ operation.typeOperation }}</td>
            </tr>
            <tr>
                <th>Nom_medecin</th>
                <td>{{ operation.nomMedecin }}</td>
            </tr>
            <tr>
                <th>Cout_operation</th>
                <td>{{ operation.coutOperation }}</td>
            </tr>
            <tr>
                <th>Note_operation</th>
                <td>{{ operation.noteOperation }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_operation_afficher') }}">back to list</a>

    <a href="{{ path('app_operation_edit', {'id': operation.id}) }}">edit</a>

    {{ include('operation/_delete_form.html.twig') }}
{% endblock %}