src/Entity/Actualite.php
<?php

namespace App\Entity;

use App\Repository\ActualiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ActualiteRepository::class)]
class Actualite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Théme est obligatoire")]
    private ?string $theme = null;

    #[ORM\Column(length: 255)]
     #[Assert\Url()]
    #[Assert\NotBlank(message:"Image est obligatoire")]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message:"Contenu est obligatoire")]
    #[Assert\Length(min:20,minMessage:"Minimum of 10 caracteres")]
    private ?string $contenu = null;

   /* #[ORM\Column]
    private ?int $nbr_Vue = null;*/

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_Creation = null;

    #[ORM\OneToMany(mappedBy: 'actualite', targetEntity: Commentaire::class, cascade: ['remove'])]
    private Collection $Commentaire;

    #[ORM\ManyToOne(inversedBy: 'actualite')]
    private ?Membre $membre = null;
    
    public function __toString()
    {
        return $this->theme;
    }

    public function __construct()
    {
        $this->Commentaire = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

   /* public function getNbrVue(): ?int
    {
        return $this->nbr_Vue;
    }

    public function setNbrVue(int $nbr_Vue): self
    {
        $this->nbr_Vue = $nbr_Vue;

        return $this;
    }
*/
    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_Creation;
    }

    public function setDateCreation(\DateTimeInterface $date_Creation): self
    {
        $this->date_Creation = $date_Creation;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->Commentaire;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->Commentaire->contains($commentaire)) {
            $this->Commentaire->add($commentaire);
            $commentaire->setActualite($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->Commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getActualite() === $this) {
                $commentaire->setActualite(null);
            }
        }

        return $this;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): self
    {
        $this->membre = $membre;

        return $this;
    }
}

src/Form/ActualiteType.php
<?php

namespace App\Form;

use App\Entity\Actualite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActualiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('theme')
            ->add('image')
            ->add('contenu')
          //  ->add('nbr_Vue')
            ->add('date_Creation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Actualite::class,
        ]);
    }
}

src/Controller/ActualiteController.php
<?php

namespace App\Controller;

use App\Entity\Actualite;
use App\Form\ActualiteType;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\ActualiteRepository;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpClient\HttpClient;
#[Route('/actualite')]
class ActualiteController extends AbstractController
{
    #[Route('/', name: 'app_actualite_index', methods: ['GET'])]
    public function index(ActualiteRepository $actualiteRepository): Response
    {
        return $this->render('actualite/index.html.twig', [
            'actualites' => $actualiteRepository->findAll(),
        ]);
    }
    #[Route('/actu', name: 'app_actualite_affiche', methods: ['GET'])]
    public function aff(ActualiteRepository $ActualiteRepository): Response
    {
        return $this->render('actualite/afficher.html.twig', [
            'actualites' => $ActualiteRepository->findAll(),
        ]);
    }
    #[Route('/search', name: 'app_actualite_search', methods: ['GET'])]
   
    public function search(ActualiteRepository $actualiteRepository, Request $request): JsonResponse
    {
        $query = $request->query->get('q');
   
        dump($query);

        $results = [];
        if ($query !== null) {
            $results = $actualiteRepository->createQueryBuilderForSearch($query)->getQuery()->getResult();
        }
    
        $response = [];
        foreach ($results as $result) {
            $response[] = [
                'url' => $this->generateUrl('app_actualite_singlepage', ['id' => $result->getId()]),
                'theme' => $result->getTheme(),
            ];
        }
    
        return new JsonResponse($response);
    }
     
    #[Route('/stats', name: 'app_stats')]
    public function stats(ActualiteRepository $ActualiteRepository): Response
    {
        $stats = $ActualiteRepository->getCommentsStats();

        $data = [];
        $data[] = ['Post', 'Number of Comments'];

        foreach ($stats as $acStats) {
            $data[] = [$acStats['theme'], $acStats['commentsCount']];
        }

        return $this->render('actualite/stats.html.twig', [
            'chartData' => json_encode($data),
        ]);
    }
    #[Route('/new', name: 'app_actualite_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ActualiteRepository $actualiteRepository): Response
    {
        $actualite = new Actualite();
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actualiteRepository->save($actualite, true);

         return $this->redirectToRoute('app_actualite_affiche', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actualite/new.html.twig', [
            'actualite' => $actualite,
            'form' => $form,
        ]);
    }

    #[Route('act/{id}', name: 'app_actualite_show', methods: ['GET'])]
    public function show(Actualite $actualite): Response
    {
        return $this->render('actualite/show.html.twig', [
            'actualite' => $actualite,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_actualite_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Actualite $actualite, ActualiteRepository $actualiteRepository): Response
    {
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actualiteRepository->save($actualite, true);

            return $this->redirectToRoute('app_actualite_affiche', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actualite/edit.html.twig', [
            'actualite' => $actualite,
            'form' => $form,
        ]);
    }
    #[Route('actualite/{id}', name: 'app_actualite_singlepage', methods: ['GET','POST'])]
    public function singlepage(Actualite $AR,ActualiteRepository $AcRepository,Request $request, CommentaireRepository $commentaireRepository): Response
    {
        $commentaire = new Commentaire();
      
        $formC = $this->createForm(CommentaireType::class, $commentaire);
        $formC->handleRequest($request);
     
        $httpClient = HttpClient::create();
        
        if ($formC->isSubmitted() && $formC->isValid() ) {
            $commentaire ->setActualite($AR);
                         $commentaire->setDate(new \DateTime());
                        $commentaireRepository->save($commentaire, true);
            $commentaireRepository->save($commentaire, true);
            //filter for bad words:
        //     $content = $commentaire->getText();
        //     $response = $httpClient->request('GET', 'https://neutrinoapi.net/bad-word-filter', [
        //         'query' => [
        //             'content' => $content
        //         ],
        //         'headers' => [
        //             'User-ID' => 'ysf',
        //             'API-Key' => 'y1sHojwhnPNtbeRwYt90l6nUiluLvAP6WUfH4cHDjoeMCRj2',
                   
        //         ]
        //     ]);
        //     if ($response->getStatusCode() === 200) {
        //         $result = $response->toArray();
        //         if ($result['is-bad']) {
        //             // Handle bad word found

        //             return $this->redirectToRoute('app_actualite_singlepage', ['id' => $AR->getId()], Response::HTTP_SEE_OTHER);
        //         } else {
        //             // Save comment
        //             $commentaire ->setActualite($AR);
        //             $commentaire->setDate(new \DateTime());
        //             $commentaireRepository->save($commentaire, true);
                  
        //             return $this->redirectToRoute('app_actualite_singlepage', ['id' => $AR->getId()], Response::HTTP_SEE_OTHER);
        //         }
        //     } else {
        //         // Handle API error
                
        //         return new Response("Error processing request", Response::HTTP_INTERNAL_SERVER_ERROR);
        //     } 
           
        }

        $url = $this->generateUrl('app_actualite_singlepage', ['id' => $AR->getId()], UrlGeneratorInterface::ABSOLUTE_URL);
        return $this->render('actualite/singlepage.html.twig', [
            'ac' => $AR,
            'actualites' => $AcRepository->findAll(),
            'commentaire' => $commentaire,
            'formC' => $formC->createView(),
            'share_url' => $url,
        ]);
    }
  
    #[Route('/{id}', name: 'app_actualite_delete', methods: ['POST'])]
    public function delete(Request $request, Actualite $actualite, ActualiteRepository $actualiteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$actualite->getId(), $request->request->get('_token'))) {
            $actualiteRepository->remove($actualite, true);
        }

        return $this->redirectToRoute('app_actualite_affiche', [], Response::HTTP_SEE_OTHER);
    }
}

templates/actualite/index.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Actualité index{% endblock %}

{% block body %}
    {#<h1>Post index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Theme</th>
                <th>Image</th>
                <th>Contenu</th>
                <th>Nbr_Vue</th>
                <th>Date_Creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>#}
        {#% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.theme }}</td>
                <td>{{ post.image }}</td>
                <td>{{ post.contenu }}</td>
                <td>{{ post.nbrVue }}</td>
                <td>{{ post.dateCreation ? post.dateCreation|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_post_show', {'id': post.id}) }}">show</a>
                    <a href="{{ path('app_post_edit', {'id': post.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %
        </tbody>
    </table>#}
     <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {# <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All departments</span>
                        </div>
                        <ul>
                            
                        </ul>
                    </div> #}
                </div>
                {# <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="#">
                                <div class="hero__search__categories">
                                    All Categories
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <input type="text" placeholder="What do yo u need?">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">nom
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div> #}
                            {# <div class="hero__search__phone__text">
                                <h5>+65 11.188.888</h5>
                                <span>support 24/7 time</span>
                            </div> #}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
   {#<img class="breadcrumb-section set-bg" src="{{asset ('front/img/breadcrumb.jpg') }}">#} 
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Actualite</h2>
                       
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    
                        <div class="blog__sidebar__search">
                           <form id="search-form">
                                  <input type="text" id="search-input" placeholder="par theme .." >
                               
                            </form>
                               <div id="search-results"></div>
                       
                            <script>
  $(document).ready(function() {
    // Ecouter l'événement de frappe sur le champ de recherche et le changement de date
    $('#search-input').on('keyup change', function() {
        // Récupérer la valeur du champ de recherche
        var query = $('#search-input').val();

        // Vérifier si les deux champs sont vides
        if (!query) {
            $('#search-results').html('<p>Please provide a theme</p>');
            return;
        }

        // Effectuer la recherche AJAX
        $.ajax({
            type: 'GET',
            url: '/actualite/search',
            data: {q: query},
            success: function(data) {
                var resultsDiv = $('#search-results');
                resultsDiv.empty();
                if (data.length === 0) {
                    resultsDiv.append('<p>No results found.</p>');
                } else {
                    for (var i = 0; i < data.length; i++) {
                        var result = data[i];
                        resultsDiv.append('<a href="' + result.url + '">' + result.theme + '</a>');
                    }
                }
            },
            error: function(error) {
                console.log(error);
            }
        });
    });

  
});

</script>

     
   </div>
    <style>
    
    .b{
     color:#b2b2b2;
    }
    .blog__sidebar__search {
      display: flex;
    flex-wrap: nowrap; /* changed from "wrap" to "nowrap" */
    justify-content: center;
    align-items: center;
    margin-top: 50px;
    }
    

    .blog__sidebar__search input[type="text"],
     {
       width: 300px;
	padding: 10px;
	margin-right: 10px;
	border-radius: 5px;
	border: 1px solid #ccc;
	font-size: 16px;
    }
   
    #search-results {
       margin-top: 50px;
	display: flex;
	flex-direction: column;
    }

    #search-results a {
     padding: 10px;
margin-bottom: 10px;
background-color: #f5f5f5;
color: #333;
text-decoration: none;
border-radius: 5px;
transition: background-color 0.3s ease;
box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.2);
    }

    #search-results a:hover {
    background-color: #eee;
box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.2);
    }
</style>

 </div>



                        <div class="blog__sidebar__item">
                            <h4>Types</h4>
                            <ul>
                                
                            </ul>
                        </div>
                    {#   <div class="blog__sidebar__item">
                            <h4>Recent News</h4>
                            <div class="blog__sidebar__recent">
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="img/blog/sidebar/sr-1.jpg" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h6>09 Kinds Of Vegetables<br /> Protect The Liver</h6>
                                        <span>MAR 05, 2019</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="img/blog/sidebar/sr-2.jpg" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h6>Tips You To Balance<br /> Nutrition Meal Day</h6>
                                        <span>MAR 05, 2019</span>
                                    </div>
                                </a>
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="img/blog/sidebar/sr-3.jpg" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h6>4 Principles Help You Lose <br />Weight With Vegetables</h6>
                                        <span>MAR 05, 2019</span>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Search By</h4>
                            <div class="blog__sidebar__item__tags">
                                <a href="#">Apple</a>
                                <a href="#">Beauty</a>
                                <a href="#">Vegetables</a>
                                <a href="#">Fruit</a>
                                <a href="#">Healthy Food</a>
                                <a href="#">Lifestyle</a>
                            </div>
                        </div>
                    </div>
                </div>
                #} 
                <div class="col-lg-8 col-md-7">
                    <div class="row">
                        {% for ac in actualites %}
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="blog__item">
                                <div class="blog__item__pic">
                                    <img src="{{asset(ac.image)}}" alt="">
                                </div>
                                <div class="blog__item__text">
                                    <ul>
                                        <li><i class="fa fa-calendar-o"></i> {{ ac.getDateCreation() ? ac.getDateCreation()|date('Y-m-d') : '' }}</li>
                                   {#<li><i class="fa fa-comment-o"></i> {{ ac.nbrVue}}</li>#}     
                                    </ul>
                                  {# <h5><a href="#">{{ ac.nom }}</a></h5>#} 
                                    <p>{{ ac.theme}}
                                    
                                    
                                    
                                     </p>
                                    
                                  <a href="{{ path('app_actualite_singlepage', {'id': ac.id}) }}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>  
                                </div>
                            </div>
                        </div>
                        {% endfor %} 
                        
                        
                        <div class="col-lg-12">
                            <div class="product__pagination blog__pagination">
                                <a href="#">1</a>
                                <a href="#">2</a>
                                <a href="#">3</a>
                                <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock %}


    
                     

templates/actualite/show.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Actualite{% endblock %}

{% block body %}
    <h1>Actualite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ actualite.id }}</td>
            </tr>
            <tr>
                <th>Theme</th>
                <td>{{ actualite.theme }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ actualite.image }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ actualite.contenu }}</td>
            </tr>
           {# <tr>
                <th>Nbr_Vue</th>
                <td>{{ actualite.nbrVue }}</td>
            </tr>#}
            <tr>
                <th>Date_Creation</th>
                <td>{{ actualite.dateCreation ? actualite.dateCreation|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_actualite_affiche') }}">back to list</a>

    <a href="{{ path('app_actualite_edit', {'id': actualite.id}) }}">edit</a>

    {{ include('actualite/_delete_form.html.twig') }}
{% endblock %}

templates/actualite/singlepage.html.twig
{% extends 'front/base.html.twig' %}

{% block title %}Actualite{% endblock %}

{% block body %}
    <!-- Blog Details Hero Begin -->
   
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="blog__details__hero__text">
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5 order-md-1 order-2">
                    <div class="blog__sidebar">
                        <div class="blog__sidebar__search">
                            <form action="#">
                                <input type="text" placeholder="Search...">
                                <button type="submit"><span class="icon_search"></span></button>
                            </form>
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Types</h4>
                           
                        </div>
                      {#  <div class="blog__sidebar__item">
                            <h4>News</h4>
                            <div class="blog__sidebar__recent">
                            {% for ac in actualites %}
                                <a href="#" class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="{{asset(ac.image)}}" alt="">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <br />{{ ac.theme }}</h6>
                                        <span>{{ ac.getDateCreation() ? ac.getDateCreation()|date('Y-m-d') : '' }}</span>
                                    </div>
                                </a>
                                {% endfor %} 
                                
                                
                            </div>
                        </div>
                    
                </div> #}
                <div class="col-lg-8 col-md-7 order-md-1 order-1">
                    <div class="blog__details__text">
                        <img src="{{asset(ac.image)}}" alt="">
                           <h4> Theme: {{ ac.theme }}</h4>
                        <h3>ugagzrzvgafbmézgbrlézg.</h3>
                        <p>{{ ac.contenu }}</p>
                    
                   <h2>Comments</h2>
                     {% if ac.Commentaire|length > 0 %}
                      <ul>
                            {% for comment in ac.Commentaire %}
                           <li>
                                 {{ comment.text }}
                              {#   {% if comment.getMembre() == app.user %}
                                <a href="{{ path('comment_delete', {'id': comment.id}) }}">Delete</a>
                                 {% endif %} #} 
                            </li>
                             {% endfor %}
                     </ul>
                     {% else %}
                             <p>No comments</p>
                      {% endif %}

                   {{ form_start(formC,{'attr': {'novalidate': 'novalidate'}} ) }}
                   
                     {{ form_row(formC.text, {'label': false}) }}
                    <button class="btn_Comment">{{ button_label|default('Comment') }}</button>
                     {{ form_end(formC) }} 
                     
                     <div class="blog__comment__text">
                       
                    </div>
  <div class="blog__details__widget">
  <ul>
                                        <li><h3>Partager avec :</h3></span> </li>
                                    </ul>
                                 <ul>
                                        <li><span><a href="https://www.facebook.com/sharer/sharer.php?u={{ share_url }}"><i class="fab fa-facebook"></i></a></span></li>
                                   
                                  
                                    <li><a href="https://twitter.com/intent/tweet?url={{ share_url }}"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="https://www.linkedin.com/shareArticle?mini=true&url={{ share_url }}"><i class="fab fa-linkedin-in"></i></a></li>
                                  </ul>
                                      </div>
                    <div class="blog__details__content">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="blog__details__author">
                                    <div class="blog__details__author__pic">
                                     {#<img src="{{asset ('front/img/blog/details/details-author.jpg') }}" alt="">#}   
                                    </div>
                                    <div class="blog__details__author__text">
                                    {#   <h6>{{ac.Membre}}</h6>#} 
                                     
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="blog__details__widget">
                                   
                                   
                                    <div class="blog__details__social">
                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                        <a href="#"><i class="fa fa-linkedin"></i></a>
                                        <a href="#"><i class="fa fa-envelope"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <style>
    .fa-facebook:before {
    content: "\f09a";
    color: #0c43b1;
    }
    .fa-twitter:before {
    content: "\f099";
    color: #4676d6;}
    .fa-linkedin-in:before {
    content: "\f0e1";
    color: #18243c;
}
     </style>

    <!-- Blog Details Section End -->

    <!-- Related Blog Section Begin -->
    
    <!-- Related Blog Section End -->
{% endblock %}
{#<table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ post.id }}</td>
            </tr>
            <tr>
                <th>Theme</th>
                <td>{{ post.theme }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ post.image }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ post.contenu }}</td>
            </tr>
            <tr>
                <th>Nbr_Vue</th>
                <td>{{ post.nbrVue }}</td>
            </tr>
            <tr>
                <th>Date_Creation</th>
                <td>{{ post.dateCreation ? post.dateCreation|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{{ path('app_post_index') }}">back to list</a>

    <a href="{{ path('app_post_edit', {'id': post.id}) }}">edit</a>
    {{ include('post/_delete_form.html.twig') }}
#}