src/Entity/Maladie.php
<?php

namespace App\Entity;

use App\Repository\MaladieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: MaladieRepository::class)]
class Maladie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    
  
    private ?int $id = null;
    
    
    
   
   
    
    #[ORM\Column(type:"string", length:255)]
     #[Assert\Length(
          min : 3,
          max : 50,
          minMessage: "Le nom  est trop court",
          maxMessage:"Le nom est trop long")]
      
     
    private ?string $nom = null;
     

    #[ORM\Column(type: Types::TEXT)]
     

    #[Assert\NotBlank]
    #[Assert\Length(
          min : 7,
          max : 100,
          minMessage : "La description doit contenir au moins {{ limit }} caractères",
          maxMessage : "La description doit contenir moins de {{ limit }} caractères"
     )]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    
     #[Assert\NotBlank(message:"Chat/Chien/Oiseau/Autre")]
     #[Assert\Choice(['Chien', 'Chat', 'Oiseau', 'Autre'])]
     
    private ?string $type_aniaml = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
  
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    
    private ?\DateTimeInterface $date_MAJ = null;

    #[ORM\OneToMany(mappedBy: 'maladie', targetEntity: Operation::class)]
    private Collection $Operation;

    #[ORM\OneToMany(mappedBy: 'maladie', targetEntity: Animal::class)]
    private Collection $animals;

    #[ORM\ManyToOne(inversedBy: 'maladies')]
    private ?Animal $animal = null;

    public function __toString()
    {
        return $this->nom;
    }


    public function __construct()
    {
        $this->Operation = new ArrayCollection();
        $this->animals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTypeAniaml(): ?string
    {
        return $this->type_aniaml;
    }

    public function setTypeAniaml(string $type_aniaml): self
    {
        $this->type_aniaml = $type_aniaml;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateMAJ(): ?\DateTimeInterface
    {
        return $this->date_MAJ;
    }

    public function setDateMAJ(\DateTimeInterface $date_MAJ): self
    {
        $this->date_MAJ = $date_MAJ;

        return $this;
    }

    /**
     * @return Collection<int, Operation>
     */
    public function getOperation(): Collection
    {
        return $this->Operation;
    }

    public function addOperation(Operation $operation): self
    {
        if (!$this->Operation->contains($operation)) {
            $this->Operation->add($operation);
            $operation->setMaladie($this);
        }

        return $this;
    }

    public function removeOperation(Operation $operation): self
    {
        if ($this->Operation->removeElement($operation)) {
            // set the owning side to null (unless already changed)
            if ($operation->getMaladie() === $this) {
                $operation->setMaladie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Animal>
     */
    public function getAnimals(): Collection
    {
        return $this->animals;
    }

    public function addAnimal(Animal $animal): self
    {
        if (!$this->animals->contains($animal)) {
            $this->animals->add($animal);
            $animal->setMaladie($this);
        }

        return $this;
    }

    public function removeAnimal(Animal $animal): self
    {
        if ($this->animals->removeElement($animal)) {
            // set the owning side to null (unless already changed)
            if ($animal->getMaladie() === $this) {
                $animal->setMaladie(null);
            }
        }

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->animal;
    }

    public function setAnimal(?Animal $animal): self
    {
        $this->animal = $animal;

        return $this;
    }

   
}

src/Form/MaladieType.php
<?php

namespace App\Form;

use App\Entity\Maladie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Form\Transformer;

class MaladieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class,[ 'attr' => [
                'class' => 'form-control mb-3',
            ],])
            ->add('description',TextareaType::class,[ 'attr' => [
                'class' => 'form-control mb-3',
            ],])
            ->add('type_aniaml', TextType::class,[ 'attr' => [
                'class' => 'form-control mb-3',
            ],])
            ->add('date_creation', DateType::class, [
                
                'label' => 'Date et heure de creation',
                'widget' => 'single_text',

        
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('date_MAJ', DateType::class, [
                
                'label' => 'Date et heure de mise a jour',
                'widget' => 'single_text',
                
                
                'attr' => [
                    'class' => 'form-control',
                ],
            ]);
            
            
            
            
            
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Maladie::class,
        ]);
    }
}

src/Controller/MaladieController.php
<?php

namespace App\Controller;

use App\Entity\Maladie;
use App\Form\MaladieType;
use App\Repository\MaladieRepository;
use App\Repository\ReclamationRepository;
use Dompdf\Dompdf;
use Dompdf\Options;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

#[Route('/maladie')]
class MaladieController extends AbstractController
{
    #[Route('/', name: 'app_maladie_index', methods: ['GET'])]
    public function index(Request $request,MaladieRepository $maladieRepository,PaginatorInterface $paginator): Response
    {
        $maladies=$maladieRepository->listMaladieparDate();
        $maladies = $paginator->paginate(
            $maladies,
            $request->query->getInt('page', 1),
            2
        );


        return $this->render('maladie/index.html.twig'
            ,['maladies'=>$maladies]);

    }
    #[Route("/pdf/{id}",name:"pdf", methods: ['GET'])]
    public function pdf($id,MaladieRepository $repository): Response{

        $reclamation=$repository->find($id);
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
        $dompdf = new Dompdf($pdfOptions);
        $html = $this->renderView('maladie/pdf.html.twig', [
            'pdf' => $reclamation,

        ]);
        $dompdf->loadHtml($html);

        $dompdf->setPaper('B5', 'portrait');


        $dompdf->render();

        $pdfOutput = $dompdf->output();
        return new Response($pdfOutput, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="maladie.pdf"'
        ]);

    }

    #[Route('/mal', name: 'app_maladie_afficher', methods: ['GET'])]
    public function afficher(Request $request,MaladieRepository $maladieRepository,PaginatorInterface $paginator): Response
    {

        $maladies=$maladieRepository->listMaladieparDate();
        $maladies = $paginator->paginate(
            $maladies,
            $request->query->getInt('page', 1),
            3
        );


        return $this->render('maladie/afficher.html.twig'
            ,['maladies'=>$maladies]);


    }

    #[Route('/new', name: 'app_maladie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MaladieRepository $maladieRepository): Response
    {
        $maladie = new Maladie();
        $form = $this->createForm(MaladieType::class, $maladie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $maladieRepository->save($maladie, true);

            return $this->redirectToRoute('app_maladie_afficher', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('maladie/new.html.twig', [
            'maladie' => $maladie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_maladie_show', methods: ['GET'])]
    public function show(Maladie $maladie): Response
    {
        return $this->render('maladie/show.html.twig', [
            'maladie' => $maladie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_maladie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Maladie $maladie, MaladieRepository $maladieRepository): Response
    {
        $form = $this->createForm(MaladieType::class, $maladie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $maladieRepository->save($maladie, true);

            return $this->redirectToRoute('app_maladie_afficher', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('maladie/edit.html.twig', [
            'maladie' => $maladie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_maladie_delete', methods: ['POST'])]
    public function delete(Request $request, Maladie $maladie, MaladieRepository $maladieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$maladie->getId(), $request->request->get('_token'))) {
            $maladieRepository->remove($maladie, true);
        }

        return $this->redirectToRoute('app_maladie_afficher', [], Response::HTTP_SEE_OTHER);
    }

    
}

templates/maladie/_delete_form.html.twig
<form method="post" action="{{ path('app_maladie_delete', {'id': maladie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ maladie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/maladie/_form.html.twig
{{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/maladie/afficher.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Maladies{% endblock %}

{% block body %}
    <h1>Maladie </h1>
    <input  id="myInput"  type="text" placeholder="search">
    <table class="table table-rounded" id="t"  width="100%" cellspacing="0">
        <thead>
            <tr>
                <th></th>
                <th>ID</th>
                <th>Nom du maladie</th>
                <th>Description</th>
                <th>Type d'animal</th>
                <th>Date de creation</th>
                <th>Date de mise à jour</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody id="myTable">

        {% for maladie in maladies %}
            <tr>
                <td>             <a href="{{ path('pdf',{'id': maladie.id}) }}">  <img   width="30" src="https://cdn-icons-png.flaticon.com/512/337/337946.png">  </a>
                </td>
                <td>{{ maladie.id }}</td>
                <td>{{ maladie.nom }}</td>
                <td>{{ maladie.description }}</td>
                <td>{{ maladie.typeAniaml }}</td>
                <td>{{ maladie.dateCreation ? maladie.dateCreation|date('Y-m-d') : '' }}</td>
                <td>{{ maladie.dateMAJ ? maladie.dateMAJ|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_maladie_show', {'id': maladie.id}) }}">show</a>
                    <a href="{{ path('app_maladie_edit', {'id': maladie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        <tbody id="search">
        </tbody>
    </table>

    {{ knp_pagination_render(maladies) }}
    <a href="{{ path('app_maladie_new') }}">Create new</a>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{% endblock %}

templates/maladie/edit.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Modifier Maladie{% endblock %}

{% block body %}
    <h1>Modifier Maladie</h1>

    {{ include('maladie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_maladie_afficher') }}">Back</a>

    {{ include('maladie/_delete_form.html.twig') }}
{% endblock %}

templates/maladie/index.html.twig
{% extends 'front/base.html.twig' %}

{% block title %}Maladies{% endblock %}

{% block body %}

   <h1> LISTE DES MALADIES </h1>


<section class="items-product1 pt-30">
            <div class="container">
                <div class="row">
                   
                   <table class="table table-rounded" id="t"  width="100%" cellspacing="0">
                   
        <thead>
            <tr>
                <th></th>

                <th>ID</th>
                <th>NOM DU MALADIE</th>
                <th>DESCRIPTION</th>
                <th>TYPE DE L'ANIMAL</th>
                <th>DATE DE CREATION</th>
                <th>DATE DU MISE A JOUR</th>
            </tr>
        </thead>
        <tbody>
        {% for maladie in maladies %}
            <tr>
                                                         <td>             <a href={{path ('app_operation_index')}}>  <img   width="100" src="https://img.freepik.com/premium-vector/hospital-bed-glass-sign-icon-green-shiny-button-ui-website-button_159242-7509.jpg">  </a>
                </td>
                <td>{{ maladie.id }}</td>
                <td>{{ maladie.nom }}</td>
                <td>{{ maladie.description }}</td>
                <td>{{ maladie.typeAniaml }}</td>
                <td>{{ maladie.dateCreation ? maladie.dateCreation|date('Y-m-d') : '' }}</td>
                <td>{{ maladie.dateMAJ ? maladie.dateMAJ|date('Y-m-d') : '' }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
                    {{ knp_pagination_render(maladies) }}
                </div>
            </div>
        </section>
                <div class="single-slider slider-bg2 slider-height d-flex align-items-center">
                    <div class="container">
                        <div class="row justify-content-end">
                            <div class="col-xxl-5 col-xl-6 col-lg-7 col-md-8 col-sm-10">
                                <div class="hero-caption text-center">
                                 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <section class="items-product1 pt-30">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                        <div class="single-items mb-20">
                           
                            
                        </div>
                    </div>
                   
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                        <div class="single-items mb-20">
                           
                        </div>
                    </div>
                </div>
            </div>
        </section>
    

 
{% endblock %}

templates/maladie/new.html.twig
{% extends 'base1.html.twig' %}

{% block title %}New Maladie{% endblock %}

{% block body %}
    <h1>Create new Maladie</h1>

    {{ include('maladie/_form.html.twig') }}

    <a href="{{ path('app_maladie_index') }}">Back</a>
{% endblock %}

templates/maladie/pdf.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Mon PDF personnalisé</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}" />
</head>
<body>

<h1> FICHE MALADIE </h1>

<h4>DATE DE CREATION : {{(pdf.dateCreation).format('d/m/Y')}}</h4>
<div class="header">
    <h1>NOM DU MALADIE  : {{ pdf.nom }}</h1>
</div>
<div class="content">
    <p>Description : {{ pdf.description }}</p>
</div>
<div class="footer">
    <h1>ANIMAL : {{ pdf.typeAniaml }}</h1>
</div>
</body>
</html>

<style>
    body {
        background-color: #f2f2f2;
        font-family: Arial, sans-serif;
    }

    .header {
        background-color: #008080;
        color: #fff;
        padding: 20px;
    }

    .content {
        padding: 20px;
    }

    .footer {
        background-color: #008080;
        color: #fff;
        padding: 10px;
        text-align: center;
        font-size: 12px;
    }
</style>

templates/maladie/show.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Maladie{% endblock %}

{% block body %}
    <h1>Maladie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ maladie.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ maladie.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ maladie.description }}</td>
            </tr>
            <tr>
                <th>Type_aniaml</th>
                <td>{{ maladie.typeAniaml }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ maladie.dateCreation ? maladie.dateCreation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_MAJ</th>
                <td>{{ maladie.dateMAJ ? maladie.dateMAJ|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_maladie_afficher') }}">Back</a>

    <a href="{{ path('app_maladie_edit', {'id': maladie.id}) }}">Edit</a>

    {{ include('maladie/_delete_form.html.twig') }}
{% endblock %}